// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: codebridge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is the single frame type on the wire, mirroring the previous
// WebSocket JSON envelope one-to-one so the registry layer stays intact.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // registered | request | response | progress | heartbeat
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // tool-specific JSON payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_codebridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_codebridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_codebridge_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentCode   string                 `protobuf:"bytes,1,opt,name=enrollment_code,json=enrollmentCode,proto3" json:"enrollment_code,omitempty"`
	DeviceCredential string                 `protobuf:"bytes,2,opt,name=device_credential,json=deviceCredential,proto3" json:"device_credential,omitempty"`
	DeviceId         string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName       string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Version          string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Workspaces       []*Workspace           `protobuf:"bytes,6,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	ToolPolicy       *ToolPolicy            `protobuf:"bytes,7,opt,name=tool_policy,json=toolPolicy,proto3" json:"tool_policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_codebridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codebridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_codebridge_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetEnrollmentCode() string {
	if x != nil {
		return x.EnrollmentCode
	}
	return ""
}

func (x *RegisterRequest) GetDeviceCredential() string {
	if x != nil {
		return x.DeviceCredential
	}
	return ""
}

func (x *RegisterRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *RegisterRequest) GetToolPolicy() *ToolPolicy {
	if x != nil {
		return x.ToolPolicy
	}
	return nil
}

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Writable      bool                   `protobuf:"varint,3,opt,name=writable,proto3" json:"writable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_codebridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_codebridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_codebridge_proto_rawDescGZIP(), []int{2}
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Workspace) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

type ToolPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnabledTools  []string               `protobuf:"bytes,1,rep,name=enabled_tools,json=enabledTools,proto3" json:"enabled_tools,omitempty"`
	DisabledTools []string               `protobuf:"bytes,2,rep,name=disabled_tools,json=disabledTools,proto3" json:"disabled_tools,omitempty"`
	CustomTools   []*CustomTool          `protobuf:"bytes,3,rep,name=custom_tools,json=customTools,proto3" json:"custom_tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolPolicy) Reset() {
	*x = ToolPolicy{}
	mi := &file_codebridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolPolicy) ProtoMessage() {}

func (x *ToolPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_codebridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolPolicy.ProtoReflect.Descriptor instead.
func (*ToolPolicy) Descriptor() ([]byte, []int) {
	return file_codebridge_proto_rawDescGZIP(), []int{3}
}

func (x *ToolPolicy) GetEnabledTools() []string {
	if x != nil {
		return x.EnabledTools
	}
	return nil
}

func (x *ToolPolicy) GetDisabledTools() []string {
	if x != nil {
		return x.DisabledTools
	}
	return nil
}

func (x *ToolPolicy) GetCustomTools() []*CustomTool {
	if x != nil {
		return x.CustomTools
	}
	return nil
}

type CustomTool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tool          string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	Args          map[string]string      `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomTool) Reset() {
	*x = CustomTool{}
	mi := &file_codebridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomTool) ProtoMessage() {}

func (x *CustomTool) ProtoReflect() protoreflect.Message {
	mi := &file_codebridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomTool.ProtoReflect.Descriptor instead.
func (*CustomTool) Descriptor() ([]byte, []int) {
	return file_codebridge_proto_rawDescGZIP(), []int{4}
}

func (x *CustomTool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomTool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CustomTool) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *CustomTool) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type RegisterResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Accepted         bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DeviceCredential string                 `protobuf:"bytes,3,opt,name=device_credential,json=deviceCredential,proto3" json:"device_credential,omitempty"` // set on first enrollment
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_codebridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codebridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_codebridge_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetDeviceCredential() string {
	if x != nil {
		return x.DeviceCredential
	}
	return ""
}

type AgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	Workspace     string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Args          map[string]string      `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // args values are JSON-encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_codebridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codebridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_codebridge_proto_rawDescGZIP(), []int{6}
}

func (x *AgentRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *AgentRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *AgentRequest) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type AgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_codebridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codebridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_codebridge_proto_rawDescGZIP(), []int{7}
}

func (x *AgentResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AgentResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AgentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProgressEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Event         string                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressEvent) Reset() {
	*x = ProgressEvent{}
	mi := &file_codebridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressEvent) ProtoMessage() {}

func (x *ProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_codebridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressEvent.ProtoReflect.Descriptor instead.
func (*ProgressEvent) Descriptor() ([]byte, []int) {
	return file_codebridge_proto_rawDescGZIP(), []int{8}
}

func (x *ProgressEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProgressEvent) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ProgressEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

var File_codebridge_proto protoreflect.FileDescriptor

const file_codebridge_proto_rawDesc = "" +
	"\n" +
	"\x10codebridge.proto\x12\rcodebridge.v1\"t\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\xb5\x02\n" +
	"\x0fRegisterRequest\x12'\n" +
	"\x0fenrollment_code\x18\x01 \x01(\tR\x0eenrollmentCode\x12+\n" +
	"\x11device_credential\x18\x02 \x01(\tR\x10deviceCredential\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x128\n" +
	"\n" +
	"workspaces\x18\x06 \x03(\v2\x18.codebridge.v1.WorkspaceR\n" +
	"workspaces\x12:\n" +
	"\vtool_policy\x18\a \x01(\v2\x19.codebridge.v1.ToolPolicyR\n" +
	"toolPolicy\"O\n" +
	"\tWorkspace\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bwritable\x18\x03 \x01(\bR\bwritable\"\x96\x01\n" +
	"\n" +
	"ToolPolicy\x12#\n" +
	"\renabled_tools\x18\x01 \x03(\tR\fenabledTools\x12%\n" +
	"\x0edisabled_tools\x18\x02 \x03(\tR\rdisabledTools\x12<\n" +
	"\fcustom_tools\x18\x03 \x03(\v2\x19.codebridge.v1.CustomToolR\vcustomTools\"\xc8\x01\n" +
	"\n" +
	"CustomTool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x127\n" +
	"\x04args\x18\x04 \x03(\v2#.codebridge.v1.CustomTool.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11device_credential\x18\x03 \x01(\tR\x10deviceCredential\"\xb4\x01\n" +
	"\fAgentRequest\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\x129\n" +
	"\x04args\x18\x03 \x03(\v2%.codebridge.v1.AgentRequest.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\rAgentResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"X\n" +
	"\rProgressEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05event2O\n" +
	"\fAgentService\x12?\n" +
	"\aConnect\x12\x17.codebridge.v1.Envelope\x1a\x17.codebridge.v1.Envelope(\x010\x01B,Z*github.com/edynasty/codebridge/internal/pbb\x06proto3"

var (
	file_codebridge_proto_rawDescOnce sync.Once
	file_codebridge_proto_rawDescData []byte
)

func file_codebridge_proto_rawDescGZIP() []byte {
	file_codebridge_proto_rawDescOnce.Do(func() {
		file_codebridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codebridge_proto_rawDesc), len(file_codebridge_proto_rawDesc)))
	})
	return file_codebridge_proto_rawDescData
}

var file_codebridge_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_codebridge_proto_goTypes = []any{
	(*Envelope)(nil),         // 0: codebridge.v1.Envelope
	(*RegisterRequest)(nil),  // 1: codebridge.v1.RegisterRequest
	(*Workspace)(nil),        // 2: codebridge.v1.Workspace
	(*ToolPolicy)(nil),       // 3: codebridge.v1.ToolPolicy
	(*CustomTool)(nil),       // 4: codebridge.v1.CustomTool
	(*RegisterResponse)(nil), // 5: codebridge.v1.RegisterResponse
	(*AgentRequest)(nil),     // 6: codebridge.v1.AgentRequest
	(*AgentResponse)(nil),    // 7: codebridge.v1.AgentResponse
	(*ProgressEvent)(nil),    // 8: codebridge.v1.ProgressEvent
	nil,                      // 9: codebridge.v1.CustomTool.ArgsEntry
	nil,                      // 10: codebridge.v1.AgentRequest.ArgsEntry
}
var file_codebridge_proto_depIdxs = []int32{
	2,  // 0: codebridge.v1.RegisterRequest.workspaces:type_name -> codebridge.v1.Workspace
	3,  // 1: codebridge.v1.RegisterRequest.tool_policy:type_name -> codebridge.v1.ToolPolicy
	4,  // 2: codebridge.v1.ToolPolicy.custom_tools:type_name -> codebridge.v1.CustomTool
	9,  // 3: codebridge.v1.CustomTool.args:type_name -> codebridge.v1.CustomTool.ArgsEntry
	10, // 4: codebridge.v1.AgentRequest.args:type_name -> codebridge.v1.AgentRequest.ArgsEntry
	0,  // 5: codebridge.v1.AgentService.Connect:input_type -> codebridge.v1.Envelope
	0,  // 6: codebridge.v1.AgentService.Connect:output_type -> codebridge.v1.Envelope
	6,  // [6:7] is the sub-list for method output_type
	5,  // [5:6] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_codebridge_proto_init() }
func file_codebridge_proto_init() {
	if File_codebridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codebridge_proto_rawDesc), len(file_codebridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_codebridge_proto_goTypes,
		DependencyIndexes: file_codebridge_proto_depIdxs,
		MessageInfos:      file_codebridge_proto_msgTypes,
	}.Build()
	File_codebridge_proto = out.File
	file_codebridge_proto_goTypes = nil
	file_codebridge_proto_depIdxs = nil
}
